apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-production-to-development
  namespace: production
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: NotIn
                values:
                  - development
                  - staging